#include "handler.h"
#include "handlers_impl.h"
#include <stdlib.h>
#include <string.h>

s_handlers_arr h_arr;
extern s_program p;

s_handler_entry init_handlers[] = {
    {HANDLER_LABEL, ASM_INSTR_NONE, ASM_DIR_NONE, handle_label},
    {HANDLER_INSTRUCTION, ASM_INSTR_HALT, ASM_DIR_NONE, handle_halt},
    {HANDLER_INSTRUCTION, ASM_INSTR_INT, ASM_DIR_NONE, handle_int},
    {HANDLER_INSTRUCTION, ASM_INSTR_IRET, ASM_DIR_NONE, handle_iret},
    {HANDLER_INSTRUCTION, ASM_INSTR_CALL, ASM_DIR_NONE, handle_call},
    {HANDLER_INSTRUCTION, ASM_INSTR_RET, ASM_DIR_NONE, handle_ret},
    {HANDLER_INSTRUCTION, ASM_INSTR_JMP, ASM_DIR_NONE, handle_jmp},
    {HANDLER_INSTRUCTION, ASM_INSTR_BEQ, ASM_DIR_NONE, handle_beq},
    {HANDLER_INSTRUCTION, ASM_INSTR_BNE, ASM_DIR_NONE, handle_bne},
    {HANDLER_INSTRUCTION, ASM_INSTR_BGT, ASM_DIR_NONE, handle_bgt},
    {HANDLER_INSTRUCTION, ASM_INSTR_PUSH, ASM_DIR_NONE, handle_push},
    {HANDLER_INSTRUCTION, ASM_INSTR_POP, ASM_DIR_NONE, handle_pop},
    {HANDLER_INSTRUCTION, ASM_INSTR_XCHG, ASM_DIR_NONE, handle_xchg},
    {HANDLER_INSTRUCTION, ASM_INSTR_ADD, ASM_DIR_NONE, handle_add},
    {HANDLER_INSTRUCTION, ASM_INSTR_SUB, ASM_DIR_NONE, handle_sub},
    {HANDLER_INSTRUCTION, ASM_INSTR_MUL, ASM_DIR_NONE, handle_mul},
    {HANDLER_INSTRUCTION, ASM_INSTR_DIV, ASM_DIR_NONE, handle_div},
    {HANDLER_INSTRUCTION, ASM_INSTR_NOT, ASM_DIR_NONE, handle_not},
    {HANDLER_INSTRUCTION, ASM_INSTR_AND, ASM_DIR_NONE, handle_and},
    {HANDLER_INSTRUCTION, ASM_INSTR_OR, ASM_DIR_NONE, handle_or},
    {HANDLER_INSTRUCTION, ASM_INSTR_XOR, ASM_DIR_NONE, handle_xor},
    {HANDLER_INSTRUCTION, ASM_INSTR_SHL, ASM_DIR_NONE, handle_shl},
    {HANDLER_INSTRUCTION, ASM_INSTR_SHR, ASM_DIR_NONE, handle_shr},
    {HANDLER_INSTRUCTION, ASM_INSTR_LD, ASM_DIR_NONE, handle_ld},
    {HANDLER_INSTRUCTION, ASM_INSTR_ST, ASM_DIR_NONE, handle_st},
    {HANDLER_INSTRUCTION, ASM_INSTR_CSRRD, ASM_DIR_NONE, handle_csrrd},
    {HANDLER_INSTRUCTION, ASM_INSTR_CSRWR, ASM_DIR_NONE, handle_csrwr},
    {HANDLER_DIRECTIVE, ASM_INSTR_NONE, ASM_DIR_GLOBAL, handle_global},
    {HANDLER_DIRECTIVE, ASM_INSTR_NONE, ASM_DIR_EXTERN, handle_extern},
    {HANDLER_DIRECTIVE, ASM_INSTR_NONE, ASM_DIR_SECTION, handle_s_section},
    {HANDLER_DIRECTIVE, ASM_INSTR_NONE, ASM_DIR_WORD, handle_word},
    {HANDLER_DIRECTIVE, ASM_INSTR_NONE, ASM_DIR_SKIP, handle_skip},
    {HANDLER_DIRECTIVE, ASM_INSTR_NONE, ASM_DIR_ASCII, handle_ascii},
    {HANDLER_DIRECTIVE, ASM_INSTR_NONE, ASM_DIR_EQU, handle_equ},
    {HANDLER_DIRECTIVE, ASM_INSTR_NONE, ASM_DIR_END, handle_end},
};

void init_handler_arr()
{
    h_arr.size = HANDLERS_START_SIZE;
    h_arr.entries = (s_handler_entry*)malloc(sizeof(s_handler_entry) * h_arr.size);
    h_arr.next_avail = 0;
}
